# Generated by Django 5.2.3 on 2025-06-22 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Noms')),
                ('sname', models.CharField(max_length=50, verbose_name='Prénoms')),
                ('email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('mot_de_passe', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('active', models.CharField(choices=[('Actif', 'Actif'), ('Non Actif', 'Non Actif')], default='Actif', max_length=10, verbose_name='Statut')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Etudiant dévéloppeur',
                'verbose_name_plural': 'Etudiants dévéloppeurs',
                'db_table': 'DevStudents',
            },
        ),
    ]
